version: '3'

networks:
  worldpress:

services:
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./web:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - worldpress
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8088:80"
    volumes:
      - ./web:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - php
      - mysql
      - phpmyadmin
    networks:
        - worldpress

  mysql:
    image: mysql:5.7
    ports:
      - "4306:3306"
    environment:
      MYSQL_DATABASE: store
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123
      MYSQL_ROOT_PASSWORD: 123
    networks:
      - worldpress
    volumes:
      - ./data/mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    links: 
      - mysql:mysql
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123
      MYSQL_ROOT_PASSWORD: 123
    networks:
      - worldpress
    depends_on:
      - mysql